name: CI

on:
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for make test
          submodules: "recursive"

      - name: Install host dependencies
        run: |
          sudo apt-get update
          sudo apt-get install flatpak flatpak-builder mutter

      # Restore caches
      - name: Restore Flatpak dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/.local/share/flatpak
          key: ${{ runner.os }}-flatpak-dependencies-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-flatpak-dependencies-

      - run: mutter --wayland --no-x11 --headless --wayland-display=wayland-0 --virtual-monitor 1280x720 > /tmp/mutter.log 2>&1 &
      - run: make ci
      - run: cat /tmp/mutter.log

      # Save caches
      - name: Save Flatpak dependencies
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ~/.local/share/flatpak
          key: ${{ runner.os }}-flatpak-dependencies-${{ github.run_id }}
